//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAssignment
    {
        public DailyAssignment()
        {
            this.Quantity = 0;
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Meal Meal { get; set; }
        public virtual DietType DietType { get; set; }
    }
}
