//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.DailyAssignment = new HashSet<DailyAssignment>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
    
        public virtual ICollection<DailyAssignment> DailyAssignment { get; set; }
    }
}
